_wandb:
    value:
        cli_version: 0.27.0
        e:
            znf9hfdaoyddwpa91s7w216595i3wmih:
                codePath: ai\train\train.py
                codePathLocal: ai\train\train.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999630565376"
                        used: "661242683392"
                email: josealfredo.zambranacruz.az@gmail.com
                executable: C:\Users\alfre\Documents\Tarts\Coding\proyectos\BWAI_project_soyaLens\envBWIA\Scripts\python.exe
                git:
                    commit: 93c4e5a166dea05dfb719ec1ebc3604bd468e68a
                    remote: https://github.com/AlfredoZC/soyaLens.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-a99c6491-8bbf-13ee-c7a6-1466c7149ddd
                host: MSI
                memory:
                    total: "16868859904"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\alfre\Documents\Tarts\Coding\proyectos\BWAI_project_soyaLens\soyaLens\ai\train\train.py
                python: CPython 3.10.9
                root: C:\Users\alfre\Documents\Tarts\Coding\proyectos\BWAI_project_soyaLens\soyaLens
                startedAt: "2026-05-30T13:54:44.069465Z"
                writerId: znf9hfdaoyddwpa91s7w216595i3wmih
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.9
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
classes:
    value:
        - broken
        - immature
        - intact
        - damaged
dataset:
    value: soyalens-granos
model:
    value: yolo26s
nc:
    value: 4
